# Generated by Django 5.0.3 on 2024-03-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_category",
                    models.CharField(
                        choices=[
                            ("Wound Care", "Wound Care"),
                            ("Colo-Rectal Care", "Colo-Rectal Care"),
                            ("Uro Care", "Uro Care"),
                            ("Orthopedic", "Orthopedic"),
                            ("Vericose Vein", "Vericose Vein"),
                            ("Abscess and Cyst", "Abscess and Cyst"),
                            ("Corn and Warts", "Corn and Warts"),
                            ("Planter Fascitis", "Planter Fascitis"),
                            ("Hydrocele", "Hydrocele"),
                            ("Musculoskeletal Disorder", "Musculoskeletal Disorder"),
                            ("Diabetes", "Diabetes"),
                            ("Hypertension", "Hypertension"),
                            ("Obesity", "Obesity"),
                            ("Paralysis", "Paralysis"),
                            ("Artheritis", "Artheritis"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
    ]
